### ISSUE TITLE
[Feature Request] Add Ability to Initiate Per-room cleaning

### ISSUE THREAD

**Issue by LudusLight** [alanjames1987/Wyze-HA#3]
Add functionality to specify the room(s) to clean when cleaning

**Comment by alanjames1987** [comment]
I've added this using the ability to send custom commands. The only command available right now is `segmented_cleanup` which accepts a parameter called `segment_ids`. This signature intentionally matches [Valetudo RE's room cleaning commands](https://github.com/rand256/valetudo/blob/testing/lib/MqttClient.js#L19).

To run it do something like this in Home Assistant:

```yaml
service: vacuum.send_command
target:
  entity_id: vacuum.my_vaccuum # this is your vacuum entity
data:
  command: segmented_cleanup
  params:
    segment_ids:
      - Bedroom # this is a list of rooms you want to clean based on the name you gave them in the Wyze app

```
